
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xa5\x8d\xb4;e+\x0b\xaad\xed\xd2\to\x0bK\xd0'
    
_lr_action_items = {'ID':([3,],[4,]),'TIPO':([0,],[3,]),'$end':([1,2,4,],[0,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'primario':([0,],[1,]),'declaracao':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> primario","S'",1,None,None,None),
  ('primario -> declaracao','primario',1,'p_primario_decl','naja.py',107),
  ('declaracao -> TIPO ID','declaracao',2,'p_declaracao','naja.py',110),
]
